proto_library (
  name = "rpcservice_proto",
  srcs = [
    "rpcservice.proto",    
  ],
  deps = [
    ":rpc_proto",
  ],
)


proto_library (
  name = "rpc_proto",
  srcs = [
    "rpc.proto",    
  ],
)
