cc_library (
  name = "protobuf",
  srcs = [
  "ProtobufCodecLite.cc",
  ],
  deps = [
    "//thirdparty/boost:boost_date_time",
    '//thirdparty/boost:boost_locale',
    "//thirdparty/boost:boost_system",
    "//thirdparty/boost:boost_thread",
    "#pthread",
    "#rt",
    "#libz",
  ])
