cc_library (
  name = "cdns",
  srcs = [
    "dns.cc",
      "Resolver.cc",
  ],
  deps = [
    "//muduo/base:libbase",
    "//muduo/net:libnet",
    "//thirdparty/boost:boost_date_time",
    '//thirdparty/boost:boost_locale',
    "//thirdparty/boost:boost_system",
    "//thirdparty/boost:boost_thread",
    "#pthread",
  ])

